export const STORAGE_PREFIX = 'xt_react_'
export const SYS_CONFIG = 'sys_config'
export const USER = 'user'
// export const TOKEN = 'token'
// export const DEFAULT_LANGUAGE = 'default-language'
// export const Element_SIZE = 'element-size'
// export const COLOR_SCHEME = 'color-scheme'
// export const THEME = 'theme'
